const communityStorageKey='agri_community_demo_v1';
const communityReactionTypes=['helpful','heart','celebrate'];
function communitySeed(){return {posts:[
  {id:'welcome-harvest',authorId:null,author:'Ramon Dimaculangan',role:'farmer',location:'Batangas',text:'Salamat sa payo ng AgrikAIzen! Tumaas ang average yield ng aming RC 218 rice ng halos 18% kumpara noong nakaraang taon.',category:'harvest',createdAt:'2026-10-02T06:00:00.000Z',reactions:{helpful:[],heart:[],celebrate:[]},comments:[]},
  {id:'welcome-tip',authorId:null,author:'Maria Santos',role:'coop',location:'Benguet',text:'Mag-ingat sa peste ng Rice Black Bug ngayong papalapit ang kabilugan ng buwan. Panatilihin ang tamang antas ng tubig at obserbahan ang palayan.',category:'tip',createdAt:'2026-10-02T03:00:00.000Z',reactions:{helpful:[],heart:[],celebrate:[]},comments:[]}
]}}
function demoCommunity(){let data;try{data=JSON.parse(localStorage.getItem(communityStorageKey)||'null')}catch{}if(!data?.posts){data=communitySeed();localStorage.setItem(communityStorageKey,JSON.stringify(data))}data.posts.forEach(p=>{p.reactions=p.reactions||{};communityReactionTypes.forEach(x=>p.reactions[x]=Array.isArray(p.reactions[x])?p.reactions[x]:[]);p.comments=Array.isArray(p.comments)?p.comments:[]});return data}
function communityPublicPosts(db){return [...db.posts].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).map(p=>({...p,reactions:Object.fromEntries(communityReactionTypes.map(x=>[x,p.reactions[x].length])),viewerReactions:communityReactionTypes.filter(x=>p.reactions[x].includes(state.user.id)),comments:p.comments.map(c=>({...c,isOwn:c.authorId===state.user.id})),canDelete:p.authorId===state.user.id||state.user.role==='admin'}))}
function communityData(){if(state.user?.demo)return {posts:communityPublicPosts(demoCommunity())};return state.communityOwner===state.user?.id&&state.community?state.community:{posts:[]}}
async function refreshCommunity(){if(!state.user)return;const owner=state.user.id,page=state.page;if(state.user.demo){state.community=communityData();state.communityOwner=owner;state.communityLoading=false;if(state.page===page&&!shouldPreserveFormInput())render();return}state.communityLoading=true;try{const data=await api('/api/community',{action:'read'});if(state.user?.id!==owner)return;state.community=data;state.communityOwner=owner;state.communityError=''}catch(error){if(state.user?.id===owner)state.communityError=error.message}finally{if(state.user?.id===owner){state.communityLoading=false;if(state.page===page&&!shouldPreserveFormInput())render()}}}
function demoCommunityWrite(body){const db=demoCommunity(),now=new Date().toISOString(),id=crypto.randomUUID();let post;if(body.action==='createPost'){post={id,authorId:state.user.id,author:state.user.name,role:state.user.role,location:state.user.location,text:body.text.trim(),category:body.category,createdAt:now,reactions:{helpful:[],heart:[],celebrate:[]},comments:[]};db.posts.push(post)}else{post=db.posts.find(p=>p.id===body.postId);if(!post)throw new Error(t('Hindi nakita ang post.','Post not found.'));if(body.action==='toggleReaction'){const users=post.reactions[body.reaction],i=users.indexOf(state.user.id);i>=0?users.splice(i,1):users.push(state.user.id)}else if(body.action==='addComment'){post.comments.push({id,authorId:state.user.id,author:state.user.name,role:state.user.role,text:body.text.trim(),createdAt:now})}else if(body.action==='deletePost'){if(post.authorId!==state.user.id&&state.user.role!=='admin')throw new Error(t('Sarili mong post lamang ang maaaring burahin.','You can only delete your own posts.'));db.posts.splice(db.posts.indexOf(post),1)}}localStorage.setItem(communityStorageKey,JSON.stringify(db));return {posts:communityPublicPosts(db)}}
async function communityWrite(body){if(state.user.demo)return demoCommunityWrite(body);return api('/api/community',body)}
function communityRole(role){return {farmer:t('Magsasaka','Farmer'),buyer:t('Mamimili','Buyer'),coop:t('Kooperatiba','Cooperative'),logistics:'Logistics',admin:'Admin'}[role]||t('Miyembro','Member')}
function communityAvatar(role){return {farmer:'👨🏽‍🌾',buyer:'🛒',coop:'🤝',logistics:'🚚',admin:'🛡️'}[role]||'👤'}
function communityTime(value){const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return t('Ngayon lang','Just now');if(seconds<3600)return `${Math.floor(seconds/60)}m`;if(seconds<86400)return `${Math.floor(seconds/3600)}h`;if(seconds<604800)return `${Math.floor(seconds/86400)}d`;return new Intl.DateTimeFormat(isEn()?'en-PH':'fil-PH',{month:'short',day:'numeric'}).format(new Date(value))}
function categoryName(category){return {general:t('Kuwento','Story'),question:t('Tanong','Question'),tip:t('Payo','Tip'),harvest:t('Ulat Ani','Harvest update'),market:t('Merkado','Market')}[category]||t('Kuwento','Story')}
function reactionButton(post,type,emoji,fil,en){const active=post.viewerReactions.includes(type);return `<button type="button" class="reaction-btn ${active?'active':''}" aria-pressed="${active}" onclick="toggleCommunityReaction('${post.id}','${type}')"><span>${emoji}</span><b>${t(fil,en)}</b><small>${post.reactions[type]||0}</small></button>`}
function communityPost(post){const comments=post.comments||[],confirming=state.communityDeleteId===post.id;return `<article class="card community-post"><div class="community-author"><div class="partner-avatar">${communityAvatar(post.role)}</div><div class="grow"><b>${esc(post.author)}</b><p class="muted small">${communityRole(post.role)} · ${esc(post.location||'Pilipinas')} · ${communityTime(post.createdAt)}</p></div>${post.canDelete?`<button type="button" class="post-menu" onclick="askDeleteCommunityPost('${post.id}')" aria-label="${t('Burahin ang post','Delete post')}">⋮</button>`:''}</div><span class="tag">${categoryName(post.category)}</span><p class="community-text">${esc(post.text)}</p><div class="reaction-row">${reactionButton(post,'helpful','👍','Kapaki-pakinabang','Helpful')}${reactionButton(post,'heart','❤️','Suporta','Support')}${reactionButton(post,'celebrate','🎉','Tagumpay','Celebrate')}</div>${confirming?`<div class="delete-confirm" role="alert"><b>${t('Burahin ang post na ito?','Delete this post?')}</b><div><button class="btn danger" onclick="deleteCommunityPost('${post.id}')">${t('Oo, burahin','Yes, delete')}</button><button class="btn ghost" onclick="cancelDeleteCommunityPost()">${t('Kanselahin','Cancel')}</button></div></div>`:''}<section class="comments"><h3>💬 ${t('Mga komento','Comments')} (${comments.length})</h3>${comments.length?comments.map(c=>`<div class="comment"><b>${esc(c.author)}</b><span>${communityRole(c.role)} · ${communityTime(c.createdAt)}</span><p>${esc(c.text)}</p></div>`).join(''):`<p class="muted small">${t('Wala pang komento. Mauna sa usapan.','No comments yet. Start the conversation.')}</p>`}<form class="comment-form" onsubmit="addCommunityComment(event,'${post.id}')"><label class="sr-only" for="comment-${post.id}">${t('Magkomento','Add a comment')}</label><input id="comment-${post.id}" maxlength="300" required placeholder="${t('Isulat ang komento…','Write a comment…')}"><button class="btn soft" type="submit">${t('Ipadala','Send')}</button></form></section></article>`}
function communityPage(){const data=communityData(),posts=data.posts||[];return `<section class="page soft-page community-page">${pageTop(t('Pamayanan','Community'))}<p class="page-intro">${t('Magbahagi ng karanasan, magtanong, at tumulong sa kapwa AgrikAIzen users.','Share experiences, ask questions, and help other AgrikAIzen users.')}</p><form class="card community-compose" onsubmit="createCommunityPost(event)"><div class="row"><div class="partner-avatar">${communityAvatar(state.user.role)}</div><div><b>${esc(state.user.name)}</b><p class="muted small">${communityRole(state.user.role)}</p></div></div><div class="field"><label for="communityText">${t('Ano ang nais mong ibahagi?','What would you like to share?')}</label><textarea id="communityText" maxlength="700" required rows="4" placeholder="${t('Magbahagi ng ani, payo, tanong, o balita…','Share a harvest update, tip, question, or news…')}"></textarea><small class="character-help">${t('Hanggang 700 karakter','Up to 700 characters')}</small></div><div class="compose-actions"><label for="communityCategory">${t('Uri','Category')}</label><select id="communityCategory"><option value="general">${t('Kuwento','Story')}</option><option value="question">${t('Tanong','Question')}</option><option value="tip">${t('Payo','Tip')}</option><option value="harvest">${t('Ulat Ani','Harvest update')}</option><option value="market">${t('Merkado','Market')}</option></select><button class="btn" type="submit">${t('I-post','Post')}</button></div></form>${state.user.demo?`<p class="notice">${t('Demo: ang mga post at interaction ay nase-save lamang sa browser na ito.','Demo: posts and interactions are saved only in this browser.')}</p>`:''}${state.communityError?`<p class="notice" role="alert">${esc(state.communityError)} <button class="link" onclick="refreshCommunity()">${t('Subukan muli','Retry')}</button></p>`:''}<div class="community-feed" aria-live="polite">${state.communityLoading&&!posts.length?`<p class="empty">${t('Kinukuha ang mga post…','Loading posts…')}</p>`:posts.length?posts.map(communityPost).join(''):`<p class="empty">${t('Wala pang post. Magsimula ng usapan!','No posts yet. Start the conversation!')}</p>`}</div></section>`}
async function createCommunityPost(event){event.preventDefault();const button=event.target.querySelector('button[type="submit"]'),text=$('#communityText').value.trim();if(!text)return;button.disabled=true;try{const data=await communityWrite({action:'createPost',text,category:$('#communityCategory').value});state.community={posts:data.posts};state.communityOwner=state.user.id;render();toast(t('Na-post na sa Pamayanan.','Posted to the Community.'))}catch(error){toast(error.message);button.disabled=false}}
async function toggleCommunityReaction(postId,reaction){try{const data=await communityWrite({action:'toggleReaction',postId,reaction});state.community={posts:data.posts};state.communityOwner=state.user.id;render()}catch(error){toast(error.message)}}
async function addCommunityComment(event,postId){event.preventDefault();const input=event.target.querySelector('input'),button=event.target.querySelector('button'),text=input.value.trim();if(!text)return;button.disabled=true;try{const data=await communityWrite({action:'addComment',postId,text});state.community={posts:data.posts};state.communityOwner=state.user.id;render();toast(t('Naidagdag ang komento.','Comment added.'))}catch(error){toast(error.message);button.disabled=false}}
function askDeleteCommunityPost(postId){state.communityDeleteId=postId;render()}
function cancelDeleteCommunityPost(){state.communityDeleteId=null;render()}
async function deleteCommunityPost(postId){try{const data=await communityWrite({action:'deletePost',postId});state.communityDeleteId=null;state.community={posts:data.posts};state.communityOwner=state.user.id;render();toast(t('Nabura ang post.','Post deleted.'))}catch(error){toast(error.message)}}
if(typeof window!=='undefined')Object.assign(window,{refreshCommunity,createCommunityPost,toggleCommunityReaction,addCommunityComment,askDeleteCommunityPost,cancelDeleteCommunityPost,deleteCommunityPost});
